export const generalInfo = {
  'А': [`The letter "А" in Russian is equivalent to the English letter "A". In its capital form, it looks identical to the "A" in the Latin alphabet. It shares visual similarities with its English counterpart and is pronounced similarly.`],
  'Б': [`The letter "<b>Б</b>" (B) is the Russian equivalent of the English letter <b>B</b>.<br><br>The uppercase version of this letter resembles the English <b>B</b> but with a broken-out piece, while the lowercase version has a curvy top rather than a straight one, similar to the number 6. Despite these differences, they look similar.`],
  'В': [`Pay attention whenever you come encounter a letter resembling the English letter B in Russian, it's not actually the letter B, but rather the letter <b>Ve</b>.<br><br>Russian stands out as it employs a distinct letter for the B sound, which its sound is similar to the V in Vienna, however with a different visual representation. At the end of a word, it can be pronounced like '<i>f</i>'.`],
  'Г': [`The letter "<b>Г</b>" (Ge) in Russian is equivalent to the English letter "G". The pronunciation of "Г" is similar to the English "G" as in "good" or "game". At the end of a word, it can be pronounced similar to '<i>k</i>'.<br><br>It's often used to represent the sound of the English letter "H" in borrowed words from languages that use the Latin alphabet, like English. This adaptation has been common since the 16th century. For example, in Russian, "Haiti" is spelled as "<b>Гаити</b>" (Gaiti) and "Hong Kong" as "<b>Гонконг</b>" (Gonkong). However, not all borrowed words follow this rule, especially those adopted more recently.<br><br>To help you remember the letter '<b>Г</b>', imagine it as the shape of a <b>G</b>allows in the game hangman. Or if you are familiar with basic Hangul, the Korean alphabet, you can view it as if "<b>ㄱ</b>" (G) were reflected as "<b>Г</b>" in Cyrillic/Russian.`],
  'Д': [`This letter is equivalent to the English letter "D". The pronunciation of "Д" is similar to the English "D" as in "dog" or "day".<br></br>A good mnemonic is to visualize Д as a distorted D with legs, as if it's <b>D</b>ancing.`],
  'Е': [`This letter resembles its counterpart in the Latin alphabet, However, in Russian, it goes by the name "<b>Ye</b>" and is often pronounced as "Ye," as heard in "<b>Ye</b>s", <b>нет</b>" (nyet; not) and <b>Тема</b> (tye-ma), rather than simply "E".`],
  'Ё': [`The letter "<b>Ё</b>" resembles the letter "E" in appearance, but with two dots above it, known as diaeresis. This letter is unique to the Russian orthography and is pronounced as "<b>Yo</b>". The pronunciation is similar to the combination "YO" as heard in words like "Yo-Yo" or "Yosemite".<br></br>However, it's common for Russians to omit the two dots (diaeresis) above the "е" and write it simply as "е" especially in informal contexts like text messages or casual writing. But in serious contexts like books, newspapers, and educational materials, the two dots are usually added to make sure the spelling is clear and correct.<br><br>To paint a picture, imagine the "<b>Ё</b>" as if the English letter "E" had two <b>Y</b>o<b>Y</b>os floating above it.`],
  'Ж': [`The letter "Ж" (Zhe) in Russian is equivalent to the English letter "Zh".<br></br>The sound of "Ж" resembles the buzzing of an insect, reflecting its appearance. When spoken, it imitates the fluttering noise of an insect, "zh-zh-zh...". It's similar to the English "s" in words like "pleasure" and "measure".`],
  'З': [`The letter "З" (Ze) in Russian is equivalent to the English letter "Z",, pronounced similarly to the 'Z' in 'zoo' or 'zebra'. Its appearance may be surprising, as it resembles the numeral 3.`],
  'И': [`The letter "И" (I) in Russian is equivalent to the English letter "I". The pronunciation of "И" is similar to the "ee" in "see" or "bee".`],
  'Й': [`The letter Й (short I) is similar to the Russian letter И with a wave added over it and represents a short version of the Russian vowel "И". Usually transliterated as "Y" due to its similar sound, it mainly appears before consonants or at the end of words.<br><br>Many Russian words end with <b>-ий</b> (-iy), where both the Russian letter И and the short I are juxtaposed.`],
  'К': [`The letter "К" (Ka) in Russian is equivalent to the English letter "K". The pronunciation of "К" is similar to the "k" in "kite" or "king".`],
  'Л': [`The letter "Л" (El) in Russian is equivalent to the English letter "L". The pronunciation of "Л" is similar to the "l" in "lamp" or "lemon".<br><br>To memorize this letter, imagine it as a pair of <b>L</b>egs extending downward from the waist.`],
  'М': [`The letter "М" (Em) in Russian is equivalent to the English letter "M". The pronunciation of "М" is similar to the "m" in "mango" or "map".`],
  'Н': [`The letter '<b>Н</b>' in Russian is similar to the English letter '<b>N</b>'. It's pronounced similarly to the English '<b>N</b>' , as in words like "<i>net</i>".<br><br>Although it might look similar to the Latin letter "<b>H</b>", '<b>Н</b>' actually resembles the letter '<b>N</b>' more closely, since both letters consist of two vertical lines joined by a line in the middle.<br><br>To facilitate your association of this Russian letter with the letter 'N', a key distinguishing feature lies only in the orientation of the connecting line: in '<b>Н</b>', it is horizontal, whereas in '<b>N</b>', it is diagonal.`],
  'О': [`The letter "О" (O) in Russian is like the English "O", but its sound can change depending on the syllable's accentuation.<br><br>In a tonic (stressed) syllable, it is pronounced as "O", while in an unstressed syllable, it is pronounced as "A". For example, in the word "Око" (Oko; eye), the first syllable is stressed, so "O" is pronounced as "O". However, in the word "Окно" (Okno; window), the first syllable is unstressed, so "O" is pronounced as "A". This phonetic shift also occurs in words like "Молоко" (milk) and "Вода" (water), where the "O" sound changes to "A" in unstressed syllables.<br><br>Understanding this accentuation pattern is crucial for accurate pronunciation of Russian words.`],
  'П': [`The letter "П" (Pe) in Russian is equivalent to the English letter "P". The pronunciation of "П" is similar to the "p" in "potato" or "park".<br><br>This letter is often compared to the Greek mathematical symbol "π" (pi) due to their visual similarity. So, this can serve as mnemonic to remember the pronunciation of "П" as "P."`],
  'Р': [`The letter "Р" (Er) in Russian is equivalent to the English letter "R". Its pronunciation, similar to the "r" in "rain" or "rabbit", can be easily associated with the sound of "R".<br><br>For mnemonic reason, imagine adding a missing diagonal stroke to "Р" to form the letter "R".`],
  'С': [`The letter 'С' (Es) in Russian is equivalent to the English letter 'S'. Although it resembles the English letter 'C', its pronunciation is similar to 'S'. You can pronounce 'С' similar to the 's' in 'sun' or 'sandwich'.<br><br>To help you remembering, whenever you encounter the letter 'С' in a Russian word, imagine it as if it were connected at the bottom to its mirrored counterpart, forming the shape of 'S', like this:<br><br>с<br>ↄ<br><br>This approach may help you initially to concatenate the Russian letter 'С' with 'S'.`],
  'Т': [`The letter "Т" (Te) in Russian is equivalent to the English letter "T". The pronunciation of "Т" is similar to the "t" in "table" or "tree".`],
  'У': [`The letter "У" (U) in Russian is equivalent to the English letter "U". The pronunciation of "У" is similar to the "oo" in "boot" or "moon".<br><br>To help you assoaciate this letter, think of the Russian У as a catap<b>U</b>lt.`],
  'Ф': [`The letter "Ф" (Ef) in Russian is equivalent to the English letter "F". The pronunciation of "Ф" is similar to the "f" in "fish" or "flag".<br><br>To help you associate this letter, consider that Ф resembles a <b>F</b>ootbal <b>F</b>ield by its visual similarity. Alternatively, if you're familiar with the golden ratio symbol, imagine the Greek letter Φ (Phi).`],
  'Х': [`The letter "Х" (Kha; H) in Russian is equivalent to the English letter "Kh". The pronunciation of "Х" is similar to english letter <b>H</b> and the <b>ch</b> in Scots lo<b>ch</b> or German Ba<b>ch</b>.`],
  'Ц': [`The letter "Ц" (Tse) in Russian is equivalent to the English letter "Ts". The pronunciation of "Ц" is similar to the "ts" in "cats</b>" or "bits".`],
  'Ч': [`The letter "Ч" (Che) in Russian is equivalent to the English letter "Ch". The pronunciation of "Ч" is similar to the "ch" in "chair" or "church".<br><br>To remember this word easily, just picture Ч (Che) as an upside-down <b>CH</b>air.`],
  'Ш': [`The letter "Ш" (Sha) in Russian is equivalent to the English letter "Sh". The pronunciation of "Ш" is similar to the "sh" in "shoe", "ship" or ""shop".<br><br>It's worth noting that in Russian, this sound combination is represented by a single letter, "Ш," yet it is commonly transliterated as "SH." `],
  'Щ': [`The letter "Щ" (Shcha) in Russian is a softer variation of "Ш" (Sha) and is equivalent to the English letter "Shch". The pronunciation of "Щ" is similar to the "shch" in "fresh" or "fashion".<br><br>Originally, its pronunciation combined the sounds of SH and CH, a trait still retained in Ukrainian. However, in Russian, its pronunciation has evolved to resemble a soft SH, similar to the sound in the English word "sheep." Despite this evolution, its transliteration remains as SHCH.`],
  'Ъ': [`The letter "Ъ" (Hard Sign) in Russian is called the "hard sign". It doesn't have a specific pronunciation but is used to indicate a hard consonant sound, typically after a consonant at the end of a word.<br><br>Serving as the counterpart to the soft sign, it modifies pronunciation by enforcing a non-palatalized sound in certain letter combinations, such as Es+Ye. While relatively rare in usage, the hard sign (ъ) is easily recognizable due to its striking resemblance to the soft sign (ь).<br><br>For recognition purposes, imagine it as an axe ready to strike the preceding letter.`],
  'Ы': [`The letter "Ы" (Y) in Russian is a unique sound that does not exist in English. It is pronounced by making a rounded lips sound while saying "ee" as in "bee".<br><br>You'll often find this letter at the end of Russian nouns to indicate plurality. For example, "кот" (kat) means "cat," but add "Ы" to make it plural: "коты" (koty) for "cats." It's the same with "дом" (dom) meaning "house" becoming "домы" (domy) for "houses".`],
  'Ь': [`The letter "Ь" (Soft Sign) in Russian, whose transliteration is ', is called the "soft sign". It doesn't have a specific pronunciation but indicates softening of the preceding consonant.<br><br>It is often silent or causes a preceding consonant to be pronounced softly. This phonetic effect, known as palatalization in linguistics, requires the tongue to approach or touch the palate (the roof of the mouth) when pronouncing soft consonants.`],
  'Э': [`The letter "Э" (E) in Russian is equivalent to the English letter "E". The pronunciation of "Э" is similar to the "e" in "pet" or "let".<br><br>Most often, the sound 'E' is represented by the letter 'Е' (Ye). To remember you easily, associate 'Э' with a mirrored <b>E</b>uro (€) sign.`],
  'Ю': [`The letter "Ю" (Yu) in Russian is equivalent to the English letter "Yu". The pronunciation of "Ю" is similar to the "yu" in "youth" or "yule".<br><br>For mnemonic purposes, imagine it as a <b>U</b>FO, kind of like the Starship Enterprise seen from a certain angle. This may help you remember both its pronunciation and shape.`],
  'Я': [`Ya (Я) is a highly common letter in the Russian alphabet. It looks like a flipped English 'R' and sounds like 'Ya.' It's the last letter in the Russian alphabet, and is often found at the end of country names.<br><br>And guess what? In Russian, 'Ya' by itself means 'I' in English! So, when you say: <b>Я учу русский язык.</b> (Ya uchu russkiy yazyk.) - you're essentially saying 'I am learning the Russian language.'`]
}

export const sentenceInfo = {
  'А': [
    '<b class="mr-1">Cities:</b> Мекка, Мао, Макао, Тема', 
    '<b class="mr-1">Type of drink:</b> Мате, какао',
    '<b class="mr-1">Fruit:</b> Томат',
    '<b>Astronomy</b>: Комета', 
    '<b class="mr-1">Female Reproductive System:</b> матка',
    '<b class="mr-1">Type of fish:</b> Кета'
  ],
  'Б': [
    '<b class="mr-1">Names:</b> Бетти, Боб',
    '<b class="mr-1">Explosive:</b> Бомба', 
    '<b class="mr-1">City in Indonesia:</b> Батам'
  ],
  'В': ['<b class="mr-1">Russian words for web, century, branch, eyelid:</b> Веб, век, Ветка, Веко'],
  'Г': [
    '<b class="mr-1">Names:</b> Гамбат, Бетагам, Готвам, Гетовам',
    '<b class="mr-1">Type of bread:</b> Багет',
    '<b class="mr-1">Russian word for gas, run and rich:</b> Газ, Бег, Богат'
  ],
  'Д': [
    '<b class="mr-1">Name:</b> Богдан',
    '<b class="mr-1">Iraq Capital:</b> Багдат',
    '<b class="mr-1">Russian word for year, when, where, yes, children, lady, house, water and hunger:</b> Год, Когда, Где, Да, Дети, Дама, Дом, Вода, Голод'
  ],
  'Е': [
    '<b class="mr-1">Name:</b> Евгения',
    '<b class="mr-1">Dangerous animal:</b> Бегемот',
    '<b class="mr-1">Village in Russia:</b> Медовка',
    '<b class="mr-1">Russian word for baby, virgin (sign) and web:</b> Детка, Дева, Веб'
  ],
  'Ё': [
    '<b class="mr-1">Name</b> Ёко',
    '<b class="mr-1">Three in Russian</b> Трёх',
    '<b class="mr-1">German writer</b> Гёте',
    '<b class="mr-1">Formal way to say honey in Russian:</b> Мёд'
  ],
  'Ж': [
    '<b class="mr-1">Russian word for hedgehog, frog and jam:</b> Ёж, Жаба, Джем',
    '<b class="mr-1">Process of cutting grass or grain:</b> Жатка',
    '<b class="mr-1">Abdomen in Russian:</b> Живот',
    '<b class="mr-1">Country:</b> Камбоджа',
  ],
  'З': [
    '<b class="mr-1">Russian word for mistery, factory, sunset, castle and star:</b> Загадка, Завод, Закат, Замок, Звезда',
    '<b class="mr-1">Animal:</b> Коза',
    '<b class="mr-1">Type of weather:</b> Гроза',
    '<b class="mr-1">Specified quantity of medication:</b> Доза'
  ],
  'И': [
    '<b class="mr-1">Russian word for pancake, whale, roof of the mouth and moment:</b> Блин, Кит, Нёбо, Миг',
    '<b class="mr-1">Russian name:</b> Вадим, Мила',
    '<b class="mr-1">Surname:</b> Виотти',
    '<b class="mr-1">Famous brand:</b> ИКЕА',
    '<b class="mr-1">Season:</b> Зима',
    '<b class="mr-1">Profession:</b> Детектив',
    '<b class="mr-1">Japan Capital:</b> Киото',
    '<b class="mr-1">Country in Asia:</b> Таиланд',
    '<b class="mr-1">Country in Africa:</b> Мозамбик'
  ],
  'Й': [
    '<b class="mr-1">Surname:</b> Жой, Гой',
    '<b class="mr-1">Type of exercise:</b> Йога',
    '<b class="mr-1">Calendar month:</b> Май',
    '<b class="mr-1">Russian word for which, bed, my, battle:</b> Кой, Койка, Мой, Бой',
    '<b class="mr-1">City in USA:</b> Майами',
    '<b class="mr-1">China in Rusian:</b> Китай',
    '<b class="mr-1">Mountainous country in eastern Siberia:</b> Алтай',
    '<b class="mr-1">Famous brands</b> Тойота, Найк',
    '<b class="mr-1">Drink</b> Глинтвейн',
    '<b class="mr-1">Chemical element</b> Йод',
  ],
  'К': ['<b class="mr-1">Russian word for cat:</b> Кот'],
  'Л': [
    '<b class="mr-1">Name:</b> Лина',
    '<b class="mr-1">Russian word for small, blockade, spoon goblet and or:</b> Мал, Блокада, Ложка, Бокал, Или',
    '<b class="mr-1">Russian city: Калуга</b>',
    '<b class="mr-1">Country in Africa: Сенегал</b>',
    '<b class="mr-1">City in Scotland:</b> Глазго',
    '<b class="mr-1">Drinks:</b> Кока-Кола, Текила, Лимонад',
    '<b class="mr-1">Loanwords from English:</b> блог, Билет'
  ],
  'М': ['<b class="mr-1">Type of drinks:</b> Мокка, Медовка'],
  'Н': [
    '<b class="mr-1">Names:</b> Тим, Данил, Анна, Натан, Нина, Нелли, Никита, Алёна, Николай',
    '<b class="mr-1">School subject:</b> Математика',
    '<b class="mr-1">Fruits:</b> Лимон, Манго, Банан',
    '<b class="mr-1">River in St Petersburg:</b> Нева',
    '<b class="mr-1">Russian word for mushroom, window, sky, ocean, team and hope:</b> Гриб, Окно, Небо, Океан, Команда, Надежда',
    '<b class="mr-1">Objects:</b> Книга, Нож, Зонт',
    '<b class="mr-1">Russian author:</b> Брежнев',
    '<b class="mr-1">Island in Sweden:</b> Готланд',
    '<b class="mr-1">Countries:</b> Канада, Гана, Конго, Того, Ангола, Монако, Оман',
    '<b class="mr-1">England Capital:</b> Лондон',
    '<b class="mr-1">Cities in Russia:</b> Магадан, Нижний',
    '<b class="mr-1">Cities:</b> Сан-Диего, Бологна',
    '<b class="mr-1">Chemical element:</b> Неон',
    '<b class="mr-1">Ideology:</b> Коммунизм',
    '<b class="mr-1">Loanwords:</b> Зомби, Момент, Банкет',
  ],
  'О': ['<b class="mr-1">Russian word for eye:</b> Око', '<b class="mr-1">Famous brand:</b> Амазон'],
  'П': [
    '<b class="mr-1">Russian name:</b> Павел',
    '<b class="mr-1">Russian word for field, lamp and ice:</b> Поле, Лампа, Лёд',
    '<b class="mr-1">Country:</b> Непал',
    '<b class="mr-1">Loanwords from English:</b> Пакет, План',
  ],
  'Р': [
    '<b class="mr-1">Names:</b> Зоро, Джордан, Мартика, Рита, Роман, Григорий',
    '<b class="mr-1">Swedish character:</b> Пеппи',
    '<b class="mr-1">Famous character:</b> Гарри Поттер',
    '<b class="mr-1">Brasilian footballer:</b> Ривалдо, Роналдо, Неймар',
    '<b class="mr-1">Russian word for truth, mountain, brother, paradise, river, grass and port:</b> Правда, Гора, Брат, Рай, Река, Трава, Порт',
    '<b class="mr-1">Aeroplane, map, friendship and journal/magazine/ week and feather in Russian:</b> Самолёт, Карта, Дружба, Журнал, Беда, Перо',
    '<b class="mr-1">Capital of Spain, France, Germany and China:</b> Мадрид, Париж, Берлин, Пекин',
    '<b class="mr-1">Language:</b> Испанский',
    '<b class="mr-1">Professions:</b> Репортёр, Актёр',
    '<b class="mr-1">Sports:</b> Карт, Карате',
    '<b class="mr-1">Place to eat:</b> Ресторан',
    '<b class="mr-1">Country:</b> Катар',
    '<b class="mr-1">Ice cream in Russian:</b> Мороженое',
    '<b class="mr-1">Animal:</b> Зебра',
    '<b class="mr-1">Cities:</b> Барселона, Портленд, Монтерей, Дрезден',
    '<b class="mr-1">Mythical creature that sucks blood:</b> Вампир',
    '<b class="mr-1">Furniture:</b> Телевизор',
    '<b class="mr-1">Element of nature:</b> Ветер ',
    '<b class="mr-1">Type of weather:</b> Гроза',
    '<b class="mr-1">Type of dessert:</b> Рирожное, Торт',
    '<b class="mr-1">Type of unit:</b> Литр',
    '<b class="mr-1">Solar System:</b> Венера',
    '<b class="mr-1">Professions:</b> Доктор, Инженер, Менеджер',
    '<b class="mr-1">Fruits:</b> Арбуз, Борис, Компот, Нектарин',
    '<b class="mr-1">Drinks:</b> Ликёр, Горилка, Портвейн, Мартини',
    '<b class="mr-1">Loanwords:</b> Коридор, Драма, Метро, Парк, Пират',
  ],
  'С': [
    '<b class="mr-1">Names:</b> Макс, Сандра, Алекс, Борис',
    '<b class="mr-1">Movie character:</b> Джеймс Бонд',
    '<b class="mr-1">Brazilian Famous Pilot:</b> Айртон Сенна',
    '<b class="mr-1">Thank you in Russian:</b> Спасибо',
    '<b class="mr-1">Famous Russian author: </b> Достоевский',
    '<b class="mr-1">Famous English actor:</b> Мистер Бин',
    '<b class="mr-1">Famous brands:</b> Пепси, Сони, МакДоналдс, Адидас',
    '<b class="mr-1">Russian word for dog, garden, dream, forest, whistle, plane and wall:</b> Собака, Сад, Сон, Лес, Свист, Самолет, Стена',
    '<b class="mr-1">Russian word for nose, table, light, power/strength, disk and sister:</b> Нос, Стол, Свет, Сила, Диск, Сестра',
    '<b class="mr-1">Russian word for butter, compass, sport, world/peace, tale and blue:</b> Масло, Компас, Спорт, Мир, Сказ, Синий',
    '<b class="mr-1">Catfish in Russian:</b> Сом',
    '<b class="mr-1">Portugual and Norway Capital:</b> Лиссабон, Осло',
    '<b class="mr-1">Cities in Russia:</b> Москова, Томска, Богородск',
    '<b class="mr-1">Countries:</b> Коста Рика, Мексика',
    '<b class="mr-1">Fruit:</b> Абрикос',
    '<b class="mr-1">Season:</b> Весна',
    '<b class="mr-1">Type of dessert:</b> Семла',
    '<b class="mr-1">Heavy animal with trunk:</b> Слон',
    '<b class="mr-1">Drink:</b> Сок',
    '<b class="mr-1">Sports:</b> Мотокросс Бокс, Теннис, Скейтборд',
    ],
  'Т': [
    '<b class="mr-1">Name:</b> Тамара',
    '<b class="mr-1">Russian word for mouth:</b> Рот',
    '<b class="mr-1">Uruguay Capital:</b> Монтевидео',
    '<b class="mr-1">City in Florida:</b> Тампа',
    '<b class="mr-1">Vegatable:</b> Томат',
  ],
  'У': [
    '<b class="mr-1">Russian word for sheet, half, meadow, rune, husband, pond:</b> Лист, Полу, Луг, Руна, Муж, Пруд',
    '<b class="mr-1">Good morning in Russian:</b> Доброе утро',
    '<b class="mr-1">Fictional japanese character:</b> Луффи, Гоку',
    '<b class="mr-1">Famous actor:</b> Том Круз',
    '<b class="mr-1">Vegetable:</b> Лук',
    '<b class="mr-1">Bird that appears in lakes:</b> Утка',
    '<b class="mr-1">Insect:</b> Жук',
    '<b class="mr-1">Famous brands:</b> Самсунг, Гугл',
    '<b class="mr-1">Yogurt in Russian:</b> Йогурт',
    '<b class="mr-1">Hand in Russian:</b> Рука',
    '<b class="mr-1">Russian author:</b> Булгаков',
    '<b class="mr-1">Solar System:</b> Сатурн',
    '<b class="mr-1">Furniture:</b> Табуретка',
    '<b class="mr-1">Countries:</b> Украина, Узбекистан',
    '<b class="mr-1">Cities in Russia:</b> Тула, Мурманск, Бугуруслан, Екатеринбург, Сургут',
    '<b class="mr-1">City:</b> Батуми',
    '<b class="mr-1">Italy Capital:</b> Рим',
    '<b class="mr-1">Fruits:</b> Клубника, Карбуз, Бута',
    '<b class="mr-1">Type of dessert:</b> Мус',
    '<b class="mr-1">Drink:</b> Рум',
    '<b class="mr-1">Traditional Slavic alcoholic drink:</b> Сатурн',
    '<b class="mr-1">Loanword:</b> Студент',
    '<b class="mr-1">Loanword from French (toilette):</b> Туалет',
  ],
  'Ф': [
    '<b class="mr-1">Names:</b> Фелипе, Жозефина, Феликс, Флора , Телефон, Фарфор, Феофан',
    '<b class="mr-1">Russian word for photo, phone, flashlight/lantern, porcelain:</b> Фото, Жозефина, Телефон, Фонарик, Фарфор',
    '<b class="mr-1">Russian word for catastrophe:</b> Катастрофа',
    '<b class="mr-1">Japanese character:</b> Луффи',
    '<b class="mr-1">School subject:</b> Физик',
    '<b class="mr-1">Famous brand</b> Майкрософт',
    '<b class="mr-1">Famous Russian author: </b> Фёдор Достоевский',
    '<b class="mr-1">Drink:</b> Кофе',
    '<b class="mr-1">Coffee Shop:</b> Кафе',
    '<b class="mr-1">Object:</b> Факс',
    '<b class="mr-1">Animals:</b> Жираф, Фламинго, Дрофа',
    '<b class="mr-1">Fruits (Фрукт):</b> Финик, Фундук',
    '<b class="mr-1">Sweet:</b> Вафли, Зефир',
    '<b class="mr-1">Drink:</b> Фраппе',
    '<b class="mr-1">Nature:</b> Фаза',
    '<b class="mr-1">Sports:</b> Футбол, Марафон',
    '<b class="mr-1">Continent:</b> Африка',
    '<b class="mr-1">Country:</b> Афганистан',
    '<b class="mr-1">Cities:</b> Франкфурт, Финикс, Мемфис',
    '<b class="mr-1">Russian city:</b> Фокино',
    '<b class="mr-1">Japanese city:</b> Фукуока',
    '<b class="mr-1">Capital city of Wales:</b> Кардифф',
    '<b class="mr-1">Loanword from English:</b> Профессор, Фонтан, Флаг, Лифт',
  ],
  'Х': [
    '<b class="mr-1">Names:</b> Хамес, Ханна, Хосе, Хуан, Харитон, Енох',
    '<b class="mr-1">Chronicle, sugar cotton and tail in Russian:</b> Хроника, Сахар, Хлопок, Хвост',
    '<b class="mr-1">Architecture in Russian:</b> Аркхитектура',
    '<b class="mr-1">Russian word for hobby, fear, church/temple, hut/cabin, bread, hill, cold:</b> Хобби, Страх, Храм, Хижина, Хлеб, Холм, Холод',
    '<b class="mr-1">German composer:</b> Бах',
    '<b class="mr-1">Fruits:</b> Хурма, Горох, Фейхоа',
    '<b class="mr-1">Cities:</b> Хайдарабад, Оклахома',
    '<b class="mr-1">City in Rusia:</b> Химки, Хабаровск',
    '<b class="mr-1">Sport:</b> Хоккей',
    '<b class="mr-1">Famous sport persons::</b> Ален Прост, Гарри Кейн',
    '<b class="mr-1">Animals:</b> Хамелеон, Хорёк',
    '<b class="mr-1">Insect:</b> Муха',
    '<b class="mr-1">Marvel fictional character:</b> Халк',
    '<b class="mr-1">Drink:</b> Херес',
    '<b class="mr-1">Traditional Slavic alcoholic drink:</b> Медовуха'
  ],
  'Ц': [
    '<b class="mr-1">Russian word for sun, bird, color, flower, cylinder:</b> Солнце, Птица, Цвет, Цветок, Цилиндр',
    '<b class="mr-1">Pizza in Russian:</b> Рицца',
    '<b class="mr-1">Vegetables:</b> Огурец, Цукини',
    '<b class="mr-1">City in USA:</b> Сан-Франциско',
    '<b class="mr-1">City in Russia:</b> Липецк',
    '<b class="mr-1">Ideology:</b> Социализм',
    '<b class="mr-1">Famous chinese politician:</b> Мао Цзэдун',
    '<b class="mr-1">Famous car brand:</b> Мерседес-Бенц',
    '<b class="mr-1">China city:</b> Циндао',
    '<b class="mr-1">Japanese rice cake:</b> Мочи',
    '<b class="mr-1">Sweets:</b> Чуррос, Чак-чак',
    '<b class="mr-1">Ice cream:</b> Гелато',
    '<b class="mr-1">Loanwords from English:</b> офицер, специалист, концерт, Центр',
  ],
  'Ч': [
    '<b class="mr-1">Russian word for pilot, now, what, hour, tea, forehead:</b> Лётчик, Сейчас, Что, Час, Чай, Чело',
    '<b class="mr-1">Butterfly in Russian and Well Done:</b> Бабочка, Молодец',
    '<b class="mr-1">Pokemon:</b> Пикачу, Чармандер',
    '<b class="mr-1">Leg cloth:</b> Чулок',
    '<b class="mr-1">Object:</b> Чайник, Чехол',
    '<b class="mr-1">Vegetables:</b> Огурец, Чеснок',
    '<b class="mr-1">Turtle and seagull:</b> Черепаха, Чайка',
    '<b class="mr-1">Communist leaders:</b> Че Гевара, Ленин',
    '<b class="mr-1">Russian composer:</b> Чайковский',
    '<b class="mr-1">Russian authors:</b> Чехов',
    '<b class="mr-1">Spider-Man in Russian:</b> Человек-паук',
    '<b class="mr-1">Country in South America:</b> Чили',
    '<b class="mr-1">Russian cities:</b> Чапаевск, Череповец',
    '<b class="mr-1">USA city:</b> Чикаго',
    '<b class="mr-1">Famous english actor:</b> Чарли Чаплин',
    '<b class="mr-1">Georgian drink:</b> Чача',
    '<b class="mr-1">Founder of Mongol Empire:</b> Чингисхан',
    '<b class="mr-1">Loanword:</b> Чемпион',
  ],
  'Ш': [
    '<b class="mr-1">Names:</b> Шива, Миша, Шарлотта, Наташа, Шерил',
    '<b class="mr-1">Famous actress:</b> Ширли Темпл',
    '<b class="mr-1">Cat (feminine) in Russian:</b> Кошка',
    '<b class="mr-1">Russian word for grandmother, sushi, chocolate, scarf, pencil, joke:</b> Бабушка, Суши, Шоколад, Шарф, Карандаш, Шутка',
    '<b class="mr-1">Food:</b> Каша',
    '<b class="mr-1">Type of artillery:</b> Пушка',
    '<b class="mr-1">Place to study:</b> Школа',
    '<b class="mr-1">A confectionery store in Russia:</b> Буше',
    '<b class="mr-1">Object:</b> Шприц',
    '<b class="mr-1">Famous character in Russia:</b> Чебурашка',
    '<b class="mr-1">Famous writers:</b> Пушкин, Шекспир',
    '<b class="mr-1">Famous detective:</b> Шерлок Холмс',
    '<b class="mr-1">Household Appliances:</b> Штора, Шкаф',
    '<b class="mr-1">Sweet:</b> Ватрушка',
    '<b class="mr-1">Vegetable:</b> Шпинат',
    '<b class="mr-1">Countries:</b> Бангладеш, Шри-Ланка',
    '<b class="mr-1">Cities:</b> Вашингтон, Шарлоттаун, Шанхай, Шарджа',
    '<b class="mr-1">Drink:</b> Шампанское',
    '<b class="mr-1">Ideology:</b> фашизм',
    '<b class="mr-1">Loanwords:</b> Шторм, Шанс, Шок, Шериф',
  ],
  'Щ': [
    '<b class="mr-1">Russian word for vegetable, woman, cheek, shield:</b> Овощ, Женщина, щека, Щит',
    '<b class="mr-1">Russian soup:</b> Борщ',
    '<b class="mr-1">Russian cities:</b> Щёлково, Щербинка, Верещагино',
  ],
  'Ъ': ['<b class="mr-1">Russian word for object, circus:</b> Объект, Цъирк',],
  'Ы': [
    '<b class="mr-1">First-person pronouns (informal and formal):</b>: Ты, Вы',
    '<b class="mr-1">First-person plural pronoun:</b>: Мы',
    '<b class="mr-1">Russian word for sup, pumpkin, fish, music, new:</b> Сыр, Тыква, Рыба, Музыка, Новый',
    '<b class="mr-1">Food:</b> Макароны',
    '<b class="mr-1">Greece Capital :</b> Афины',
    '<b class="mr-1">Clothes:</b> Мокасины, Джинсы',
    '<b class="mr-1">Country:</b> Сыр',
    '<b class="mr-1">Animal:</b> Крыса',
  ],
  'Ь': [
    '<b class="mr-1">Name:</b> Игорь',
    '<b class="mr-1">Russian word for fire, alcohol, comb, pigeon:</b> Огонь, Алкоголь, Мельница',
    '<b class="mr-1">Russian infinitive word for eating:</b> Кушать',
    '<b class="mr-1">Countries:</b> Вьетнам, Тайвань, Сьерра-Леоне',
    '<b class="mr-1">Vegatables:</b> Брокколи, Морковь',
    '<b class="mr-1">Animal that hibernates in winter:</b> Медведь',
    '<b class="mr-1">Famous car brand:</b> Фольксваген',
    '<b class="mr-1">Sport:</b> Гольф',
    '<b class="mr-1">Cities in Russia:</b> Сибирь, Тверь',
    '<b class="mr-1">Russia region:</b> Сибирь',
    '<b class="mr-1">Sweden Capital:</b> Стокгольм',
    '<b class="mr-1">Russian word for fear:</b> Страх',
    '<b class="mr-1">Russian word for thread:</b> Нить',
    '<b class="mr-1">Title of ruler:</b> ЧарЬ',
    '<b class="mr-1">Type of dances:</b>  Полька, Сальса',
    '<b class="mr-1">Loanword:</b> Отель',
  ],
  'Э': [
    '<b class="mr-1">Names:</b> Энни, Эдуард, Эльвира',
    '<b class="mr-1">Russian word for elf, this, crew/team, broadcast:</b> Эльф, Это, Экипаж, Эфир',
    '<b class="mr-1">Sweet:</b> Эклер',
    '<b class="mr-1">Famous actors:</b> Эдди Мерфи, Брэд Питт',
    '<b class="mr-1">Famous character from comics:</b> Бэтмэн',
    '<b class="mr-1">Countries:</b> Эквадор, Венесуэла',
    '<b class="mr-1">Loanwords:</b> Эффект, Экстра, Аэропорт, Аэроплан, Элемент, Экзамен, Эра'
  ],
  'Ю': [
    '<b class="mr-1">Name:</b> Юлиан, Людмила, Юрий, Ююко',
    '<b class="mr-1">Russian word for south, revolution:</b> Юг, Революция',
    '<b class="mr-1">Famous activist:</b> Мартин Лютер',
    '<b class="mr-1">Cities:</b> Дюссельдорф, Цюрих, Вильнюс',
    '<b class="mr-1">City in Russia:</b> Южно-Сахалинск',
    '<b class="mr-1">Solar System:</b> Юпитер',
    '<b class="mr-1">Russian word for storm:</b> Буря',
    '<b class="mr-1">Loanwords:</b> Парашют, бюджет'
  ],
  'Я': [
    '<b class="mr-1">Names:</b> Брюс, Юлия',
    '<b class="mr-1">Russian word for police, year and language, :</b> Полиция, Год, Язык',
    '<b class="mr-1">Fruit:</b> Яблоко',
    '<b class="mr-1">Doctor object:</b> Инъекция',
    '<b class="mr-1">Foods:</b> Лазанья, Пряники',
    '<b class="mr-1">City in USA:</b> Сантьяго',
    '<b class="mr-1">Cities in Russia:</b> Брянск, РуднЯ',
    '<b class="mr-1">Continent:</b> Азия',
    '<b class="mr-1">Countries:</b> Россия, Бразилия, Португалия, Испания, Япония, Эстония, Малайзия, Голландия, Германия, Франция, Бельгия, Швеция, Италия, Норвегия, Финляндия, Великобритания, Китай, Индия, Канада',
    '<b class="mr-1">Loanword:</b> Президент, Информация',
  ]
}
